# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.5.0"

[source]
workspace = "."
paths = ["lib", "./ryzom_extra.php"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["phpunit"]
baseline = "linter-baseline.toml"

[linter.rules]
tagged-todo = { enabled = false }
excessive-parameter-list = { enabled = false }
too-many-properties = { enabled = false }
too-many-methods = { enabled = false }
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
kan-defect = { enabled = false }
halstead = { enabled = false }
array-style = { enabled = false }
strict-types = { enabled = false }
no-empty-comment = { enabled = false }
readable-literal = { enabled = false }
assertion-style = { style = "this" }

[analyzer]
find-unused-definitions = true
find-unused-expressions = false
analyze-dead-code = false
memoize-properties = true
allow-possibly-undefined-array-keys = true
check-throws = false
check-missing-override = false
find-unused-parameters = false
strict-list-index-checks = false
no-boolean-literal-comparison = false
check-missing-type-hints = false
register-super-globals = true
baseline = "analysis-baseline.toml"
